name: test-prerelease
on:
  push:
    branches:
      - prerelease
defaults:
  run:
    shell: bash
    
jobs:
  test:
    name: Julia ${{ matrix.version }} - ${{ matrix.os }} - ${{ matrix.arch }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1.6'
          - '1.9'
          - 'nightly'
        os:
          - macOS-latest
          - windows-latest
          - ubuntu-latest
        arch:
          - x64
          - x86
        exclude:
          - os: macOS-latest
            arch: x86
          - os: ubuntu-latest
            arch: x86
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/setup-julia@latest
        with:
          version: ${{ matrix.version }}
          arch: ${{ matrix.arch }}
      - uses: julia-actions/julia-buildpkg@latest
      - uses: julia-actions/julia-runtest@latest
